### Configuration for dataset generation ###

paths:
  # The temporary directory for holding the file before upload
  tmp_dir: 'D:/temp/' 

calibrant: 'alpha_Al2O3' # Calibrant material alias string.
  
detector: 'Eiger2Cdte_1M'  # Detector type alias string.
 
wavelength:  1.54e-10 # Source wavelength in meters.

geometry_ranges:
  # Ranges for the random geometry parameters.
  # The values are given as [min, max].
  # Distance (dist) in meters.
  dist: [0.1, 0.4]
  # Poni1 in meters.
  poni1: [-0.01, 0.01]
  # Poni2 in meters.
  poni2: [-0.01, 0.01]
  # Rot1 in radians.
  rot1: [-0.001, 0.001]
  # Rot2 in radians.
  rot2: [-0.001, 0.001]
  # Rot3 in radians.
  rot3: [-0.001, 0.001]

simulation_ranges:
  # Ranges for random simulation parameters
  # Signal-to-noise ratio range [min, max].
  snr_range: [1.0, 10.0]
  # Eta parameter range [min, max].
  eta_range: [0.4, 0.6]
  # Sharpness weighting range [min, max].
  w_range: [0.1, 0.5]
  # Broadening factor range [min, max].
  broad_range: [0.5, 2.0]
  # Minimum intensity range [min, max].
  imin_range: [1.0, 5.0]
  # Maximum intensity range [min, max].
  imax_range: [100.0, 500.0]

generation:
  # Number of images to generate.
  num_images: 100
  # Division of dataset into [train, validation, test] subsets
  split_ratio: [0.8, 0.1, 0.1]
  
girder:
  # Parameters for file upload
  api_url: "data.htmdec.org/api/v1"
  parent_folder_id: "68d3f952ecbafc2edd6123a6"
  filename: "MaxViT_alpha_Al2O3_Eiger2Cdte_1M_v0_dataset.hdf5"