### Configuration for dataset generation ###

paths:
  # The temporary directory for holding the file before upload
  tmp_dir: "D:/temp"

calibrant: 'alpha_Al2O3' # Calibrant material alias string.
  
detector: 'Eiger2Cdte_1M'  # Detector type alias string.
 
wavelength:  0.54e-10 # Source wavelength in meters.

geometry_ranges:
  # Ranges for the random geometry parameters.
  # The values are given as [min, max].
  # Distance (dist) in meters.
  dist: [0.04, 0.30]
  # Poni1 in meters.
  poni1: [0.03, 0.05]
  # Poni2 in meters.
  poni2: [0.03, 0.05]
  # Rot1 in radians.
  rot1: [-0.002, 0.002]
  # Rot2 in radians.
  rot2: [-0.002, 0.002]
  # Rot3 in radians.
  rot3: [-0.002, 0.002]

simulation_ranges:
  # Ranges for random simulation parameters
  # Signal-to-noise ratio range [min, max].
  snr: [1.0, 20.0]
  # Eta parameter range [min, max].
  eta: [0.0, 1.0]
  # Sharpness weighting range [min, max].
  w_sharp: [0.000001, 0.000005]
  # Broadening factor range [min, max].
  broad_factor: [10.0, 50.0]
  # Minimum intensity range [min, max].
  imin: [0.1, 0.25]
  # Maximum intensity scaled to 1.
  imax: [1.0, 1.0]

generation:
  # Number of images to generate.
  num_images: 10000
  # Division of dataset into [train, validation, test] subsets
  split_ratio: [0.8, 0.1, 0.1]
  
girder:
  # Parameters for file upload
  api_url: "https://data.htmdec.org/api/v1"
  parent_folder_id: "68d3f952ecbafc2edd6123a6"
  filename: "MaxViT_alpha_Al2O3_Eiger2Cdte_1M_v1_dataset.hdf5"